name: hoverable_navigation_rail
description: "A HoverableNavigationRail that gives it's children an ability to use a onHover effect"
version: 1.0.0
#publish_to: 'https://pub.dev/publishers/exdock.org'
homepage: https://github.com/exDock/hoverable-navigation-rail
repository: https://github.com/exDock/hoverable-navigation-rail

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
